FROM docker.io/openjdk:8-jdk-alpine
MAINTAINER ashmastaflash

RUN apk add -U \
    bash \
    git

RUN mkdir /app
COPY ./ /app/
ENV OSH_RUNNER=/app/run_osh.sh

RUN cd /app/ && \
    ./gradlew tasks \
    ./gradlew build

EXPOSE 8181

ENTRYPOINT /bin/bash
CMD /app/launch.sh
